#!/usr/bin/perl -w
#
#  This script deletes a given message, via IMAP.
#
#  Usage:
#    delete-message folder ID
#
#  This is invoked from src/message.cc
#
#

use strict;
use warnings;

use Cwd 'abs_path';
use File::Basename;

use lib File::Basename::dirname( abs_path($0) );
use Lumail;


#
#  Arguments from the command-line.
#
my $folder = shift;
my $id     = shift;

if ( !$folder )
{
    print "Invalid command-line arguments\n";
    exit(0);
}
if ( !$id )
{
    print "Invalid command-line arguments\n";
    exit(0);
}

my $handle = Lumail::imap_connect();

# If that failed show the user and abort.
if ( !$handle )
{
    print "$0 - Login failed.\n";
    exit(0);
}

#
#  Delete
#
$handle->select($folder);
$handle->delete_message($id);
$handle->expunge();
$handle->quit();
