#!/usr/bin/perl -w
#
#  This script deletes a given message, via IMAP.
#
#  Usage:
#    delete-message folder ID
#
#
#

use strict;
use warnings;

use Net::IMAP::Client;


#
#  Arguments from the command-line.
#
my $folder = shift;
my $id     = shift;

#
# Arguments from the environment.
#
my $user = $ENV{ 'imap_username' };
my $pass = $ENV{ 'imap_password' };
my $imap = $ENV{ 'imap_server' };

#
#  Get the values we're going to connect to the IMAP server with.
#
my $port = 0;
my $ssl  = 0;
my $host = "";
if ( $imap =~ /^imaps:\/\/([^\/]+)\/?$/i )
{
    $port = 993;
    $host = $1;
    $ssl  = 1;
}
elsif ( $imap =~ /^imap:\/\/([^\/]+)\/?$/i )
{
    $port = 143;
    $host = $1;
    $ssl  = 0;
}


#
#  Create the helper
#
my $handle = Net::IMAP::Client->new(
    server          => $host,
    user            => $user,
    pass            => $pass,
    ssl             => $ssl,
    ssl_verify_peer => 0,
    port            => $port

  ) or
  die "Could not connect to IMAP server";


$handle->login or die( 'Login failed: ' . $handle->last_error() );


#
#  Delete
#
$handle->select($folder);
$handle->delete_message($id);
$handle->quit();
