#!/usr/bin/perl -w -I.
#
#  This script is invoked by luamil to read the list of globally available
# folders from a remote IMAP-server.
#
#  It is invoked from src/global_state.cc.
#
# Steve
# --


use strict;
use warnings;

use Cwd 'abs_path';
use File::Basename;
use JSON;

use lib File::Basename::dirname( abs_path($0) );
use Lumail;


my $handle = Lumail::imap_connect();

# If that failed show the user and abort.
if ( !$handle )
{
    print "$0 - Login failed.\n";
    exit(0);
}

# Get all the folders
my @folders = $handle->folders();

# Get the status of each one.
my $all = $handle->status( \@folders );

# Now build up something to return.
my $ret;

while ( my ( $name, $status ) = each %$all )
{
    push( @$ret,
          {  unread => $status->{ UNSEEN },
             total  => $status->{ MESSAGES },
             name   => $name
          } );
}

my %hash;
$hash{ 'folders' } = $ret;

my $t = JSON->new->allow_nonref;
my $o = $t->pretty->encode( \%hash );
print($o);
exit(0);
