#!/usr/bin/perl -w
#
#  This script saves the specified filename to the remote IMAP server.
#
#  It is used to archive outgoing messages when you reply, forward, or
# compose a mail, and is invoked via `lumail2.lua`.
#
# Steve
# --

use strict;
use warnings;

use Cwd 'abs_path';
use File::Basename;


use lib File::Basename::dirname( abs_path($0) );
use Lumail;


my $handle = Lumail::imap_connect();

# If that failed show the user and abort.
if ( !$handle )
{
    print "$0 - Login failed.\n";
    exit(0);
}


#
#  Arguments from the command-line.
#
my $file = shift;
if ( !$file )
{
    print "Invalid command-line arguments\n";
}

my $handle = Lumail::imap_connect();

# If that failed show the user and abort.
if ( !$handle )
{
    print "$0 - Login failed.\n";
    exit(0);
}

#
#  Get the list of folders, and their flags.
#
my $data = $handle->folders_more();

#
#  For each folder we've found look at the flags, and
# see if we can find one with `\Sent`, which is where we'll
# save the message.
#
my $sent = "";

foreach my $folder (%$data)
{
    my $entry = $data->{ $folder };

    my $flags = $entry->{ 'flags' };

    foreach my $flag (@$flags)
    {
        $sent = $folder if ( $flag =~ /\Sent/i );
    }
}

#
#  Did we find one?
#
if ($sent)
{
    my $msg = "";
    open( my $h, "<", $file ) or
      die "Failed to read $file - $!";
    while ( my $line = <$h> )
    {
        $msg .= $line;
    }
    close($h);
    $handle->append( $sent, \$msg );
}
else
{
    print "Failed to find folder to save message\n";
}

$handle->quit();
exit(0);
