Return-path: <info@meetup.com>
Envelope-to: meetup@steve.org.uk
Delivery-date: Wed, 10 Jul 2013 16:28:14 +0100
Received: from qpsmtpd (helo=ssh.steve.org.uk)
	by ssh.steve.org.uk with local-bsmtp (Exim 4.80)
	(envelope-from <info@meetup.com>)
	id 1UwwJS-0002OO-Rj
	for meetup@steve.org.uk; Wed, 10 Jul 2013 16:28:14 +0100
Received: from mail4.phi.meetup.com (HELO mail4.phi.meetup.com) (38.123.132.114)
    by mail.steve.org.uk (qpsmtpd/0.84) with ESMTP; Wed, 10 Jul 2013 16:28:14 +0100
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=meetup; d=meetup.com;
 b=B+n2eTvXMadj5pxzz8uxYjy4hDPiztYVRlbZTk3JrY53ZJ3BOOFeOtjM/+z/5YquFa7AIEtmPJ8m
   qvDxa/bSdtD5i9ZTcdwr4v2R7eIXO+eD+kEalsvdCyoyWGfOQXzx63LR3rkcYBbCee8ROji73bsF
   6w1hSFhkYrvWCaEmvWc=;
Received: from jobs0.meetup.com (10.3.0.30) by mail4.phi.meetup.com id hrluos15odg4 for <meetup@steve.org.uk>; Wed, 10 Jul 2013 11:28:13 -0400 (envelope-from <info@meetup.com>)
Message-ID: <2064850513.1373470093599.JavaMail.root@jobs0.meetup.com> (sfid-20130710_162814_948065_8A597A31)
From: The Edinburgh Digital Photography Meetup Group <info@meetup.com>
Sender: info@meetup.com
To: meetup@steve.org.uk
Subject: You're invited to National Museum of Scotland, East Kilbride- Heavy
 Horses Show
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_10387606_542281307.1373470093598"
X-MEETUP-MESG-ID: 46483812
X-MEETUP-RECIP-ID: 52304842
X-MEETUP-TRACK: ea1
Date: Wed, 10 Jul 2013 11:28:13 -0400
X-HELO: mail4.phi.meetup.com
X-REMOTE-IP: 38.123.132.114
X-REMOTE-HOST: mail4.phi.meetup.com
X-MAIL-FROM: <info@meetup.com>
X-RCPT-TO: <meetup@steve.org.uk>
X-DOMAIN: steve.org.uk
X-LOCALPART: meetup
X-CRM114-Version: 20100106-BlameMichelson ( TRE 0.8.0 (BSD) ) MR-27CA1CFB 
X-CRM114-CacheID: sfid-20130710_162814_948065_8A597A31 
X-CRM114-Status: GOOD (  55.07  )

------=_Part_10387606_542281307.1373470093598
Content-Type: multipart/alternative; 
	boundary="----=_Part_10387607_2078989503.1373470093598"

------=_Part_10387607_2078989503.1373470093598
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

CgoKCk5ldyBNZWV0dXAKCk5hdGlvbmFsIE11c2V1bSBvZiBTY290bGFuZCwgRWFzdCBLaWxicmlk
ZS0gSGVhdnkgSG9yc2VzIFNob3cKaHR0cDovL3d3dy5tZWV0dXAuY29tL19fbXM1MjMwNDg0Mi9U
aGUtRWRpbmJ1cmdoLURpZ2l0YWwtUGhvdG9ncmFwaHktTWVldHVwLUdyb3VwL2V2ZW50cy8xMjg4
NjYxNzIvdC9lYTFfZ3JwLz9ydj1lYTEmX2FmX2VpZD0xMjg4NjYxNzImX2FmPWV2ZW50JmV4cGly
ZXM9MTM3MzY0Mjg5MzU4MSZzaWc9NDE3ZDIyNjVmOTZiODEzY2RhNjgyMTFhZDI3ZTM0ZDkxODll
N2U1NQoKVGhlIEVkaW5idXJnaCBEaWdpdGFsIFBob3RvZ3JhcGh5IE1lZXR1cCBHcm91cAoKQWRk
ZWQgYnkgTWFsY29sbSBQYXJrCgpXaGVuOgpTdW5kYXksIEp1bHkgMTQsIDIwMTMKOTo0NSBQTQoK
V2hlcmU6Ck5NUyBNdXNldW0gb2YgcnVyYWwgbGlmZQpXZXN0ZXIgS2l0dG9jaHNpZGUsIEc3OSAx
QUEgKGZvbGxvdyBzaWducykKRWFzdCBLaWxicmlkZQoKCldpbGwgeW91IGF0dGVuZD8KClllcwpo
dHRwOi8vd3d3Lm1lZXR1cC5jb20vX19tczUyMzA0ODQyL1RoZS1FZGluYnVyZ2gtRGlnaXRhbC1Q
aG90b2dyYXBoeS1NZWV0dXAtR3JvdXAvZXZlbnRzLzEyODg2NjE3Mi90L2VhMV9sbm0vP3Jlc3Bv
bnNlPTMmZnJvbUVtYWlsPTEyODg2NjE3MiZhY3Rpb249cnN2cCZydj1lYTEmX2FmX2VpZD0xMjg4
NjYxNzImX2FmPWV2ZW50JnJlZnVuZF9wb2xpY3k9dHJ1ZSZleHBpcmVzPTEzNzM2NDI4OTM1ODIm
c2lnPWZiMGJhNWY1MWQzNmUzMWFhOTZiOTE2YTQ5YzBjYTI0NzkzMDgxMGUKCk5vCmh0dHA6Ly93
d3cubWVldHVwLmNvbS9fX21zNTIzMDQ4NDIvVGhlLUVkaW5idXJnaC1EaWdpdGFsLVBob3RvZ3Jh
cGh5LU1lZXR1cC1Hcm91cC9ldmVudHMvMTI4ODY2MTcyL3QvZWExX2xubS8/cmVzcG9uc2U9MiZh
Y3Rpb249cnN2cCZydj1lYTEmX2FmX2VpZD0xMjg4NjYxNzImX2FmPWV2ZW50JnJlZnVuZF9wb2xp
Y3k9dHJ1ZSZleHBpcmVzPTEzNzM2NDI4OTM1ODImc2lnPWRkYjI1NDEwZDkxOTE3MmJjOTRmODJk
NjU3MWJhMDJhMWI0ODEzZDMKCgoKCgoKRXZlbnQgZGV0YWlsczoKVGhpcyBpcyBhIGJpdCBvZiBh
IGxhc3QgbWludXRlIGlkZWEsIE5NUyBhcmUgaG9sZGluZyBhIEhlYXZ5IEhvcnNlcyBzaG93IG5l
YXIgRWFzdCBLaWxicmlkZSBvbiBzdW5kYXkgZnJvbSAxMDowMGFtIHRvIDVwbS4gVGhlIGhvcnNl
cyByYW5nZSBmcm9tIFNoZXRsYW5kIFBvbmllcyB1cCB0byBnaWFudCBDbHlkZXNkYWxlcywgc28g
dGhpcyBsb29rcyBsaWtlIGEgcHJldHR5IGdvb2QgZGF5IG91dCB3aXRoIHNvbWUgcGhvdG9ncmFw
aHkgb3Bwb3J0dW5pdGllcyB0aHJvd24gaW4uIEVudHJ5IGlzIMKjNy41MCAobWVtYmVycyBhcmUg
ZnJlZSkuIFRyYW5zcG9ydCB3b3VsZCBuZWVkIHRvIGJlIG9yZ2FuaXNlZCwgYnV0IEknbSBzdXJl
IHdlIGNhbiBjYXIgcG9vbC4gU3VnZ2VzdCB3ZSBsZWF2ZSBFZGluYnVyZ2ggYXJvdW5kIDk6NDVh
bS4gTWVldGluZyBwb2ludHMgaW4gRWRpbmJ1cmdoIHRvIGJlIGFycmFuZ2VkLgoKSSBkb24ndCB0
aGluayB0aGlzIG5lZWRzIHRvIGJlIHJlc3RyaWN0ZWQgdG8gcGhvdG9ncmFwaGVycywgc28gYW55
b25lIHdobyB3YW50cyB0byBhbG9uZy0gZ3JlYXQuCkxpbmsgdG8gTk1TIHNpdGU6IGh0dHA6Ly93
d3cubm1zLmFjLnVrL291cl9tdXNldW1zL211c2V1bV9vZl9ydXJhbF9saWZlL3doYXRzX29uL2hl
YXZ5X2hvcnNlX3Nob3cuYXNweAoKVG8gc3RvcCByZWNlaXZpbmcgZW1haWxzIHdoZW4gYSBNZWV0
dXAgaXMgYW5ub3VuY2VkLCBjbGljayBoZXJlOgpodHRwOi8vd3d3Lm1lZXR1cC5jb20vX19tczUy
MzA0ODQyL1RoZS1FZGluYnVyZ2gtRGlnaXRhbC1QaG90b2dyYXBoeS1NZWV0dXAtR3JvdXAvb3B0
b3V0Lz9zdWJtaXQ9dHJ1ZSZlbWFpbD1udU11TWFpbCZleHBpcmVzPTEzNzM2NDI4OTM1ODImc2ln
PWVmYzlhMjQ5ZTdhZmE3YmM4YTY0Yzg2NWE0ZDRkYWRjZDQxODQyOGUKCi0tIApBZGQgaW5mb0Bt
ZWV0dXAuY29tIHRvIHlvdXIgYWRkcmVzcyBib29rIHRvIHJlY2VpdmUgYWxsIE1lZXR1cCBlbWFp
bHMKClRvIG1hbmFnZSB5b3VyIGVtYWlsIHNldHRpbmdzLCBnbyB0bzogaHR0cDovL3d3dy5tZWV0
dXAuY29tL2FjY291bnQvY29tbS8KTWVldHVwLCBQT0IgNDY2OCAjMzc4OTUgTlkgTlkgVVNBIDEw
MTYzCgpNZWV0dXAgSFEgaW4gTllDIGlzIGhpcmluZyEgIGh0dHA6Ly93d3cubWVldHVwLmNvbS9q
b2JzLwo=
------=_Part_10387607_2078989503.1373470093598
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: 7bit


<!-- X-track: ea1 -->
<!-- Rsvp:  -->


				
				



<html>
        <head> 
	<title>Meetup</title>
	<style type="text/css">
		@media only screen and (max-device-width: 480px) {
		.other-meetups-tearsheet {
			display:none;
		}
		*[class=people],*[class=noFloat] {
			width: 100%!important;
			float:none!important
		}
		.showMobile {
			color:#222!important;
			line-height: 16px!important;
			max-height:20px!important;
			height:20px!important;
		}
		.hideMobile {
			color:#fff!important;
			line-height:0px!important;
			display:none!important;
		}
	}
	@media only screen and (max-device-width: 320px) {
		.event-meta,
		.event-rsvp-box,
		.noFloat,
		.event-rsvp-box-status {
			float:none!important;
			width:100%!important;
		}
		.showMobile {
			color:#222!important;
			line-height: 16px!important;
			max-height:20px!important;
			height:20px!important;
		}
		.hideMobile {
			color:#fff!important;
			line-height:5px!important;
			display:none!important;
		}
		.event-rsvp-box {
			margin-top:8px;
		}
		.other-meetups-rsvp {
			width:40%!important;
		}
		.other-meetups-event-meta {
			width:60%!important;
		}
		.event-rsvp-box-actions {
			width:100%;
		}
		*[class=people] {
			width: 100%!important;
			float:none!important
		}


	}
	@media only screen and (min-width: 10px) {
		.meetup-button-gradient {
			background-image:-webkit-gradient(linear,left top,left bottom,from(#e6304c),to(#cb1834));
			background-image:-moz-linear-gradient(center top,#e6304c,#cb1834);
			text-shadow:#b8263c -1px -1px 0;
			-moz-box-shadow:#ed6e81 1px 1px 0 0 inset;
			-webkit-box-shadow:#ed6e81 1px 1px 0 0 inset;
			-o-box-shadow:#ed6e81 1px 1px 0 0 inset;
			box-shadow:#ed6e81 1px 1px 0 0 inset;
		}
		.meetup-button-link {
			border: none!important;
			padding: 5px 18px!important;
		}
	}
	</style>
	</head> 
	<body style="margin:0;padding:0;font-family:arial;color:#333;background-color:#fff;text-align:center;">
	<div style="background:#fff!important;"> 
					<table cellpadding="0" cellspacing="0" style="width:100%;">
		<tr>
			<td style="width:49%;padding:0;border-top:1px solid #e6304c;" valign="top"><div style="height:22px;background:#e6304c;">&nbsp;</div></td>
			<td style="width:52px;padding:0;border-top:1px solid #e6304c;"><a href="http://www.meetup.com/t/ea1_1"><img src="http://www.meetup.com/t/img/ea1/logo_52x35.gif" width="52" height="39" alt="Meetup" style="border:0;" /></a></td>
			<td style="width:49%;padding:0;border-top:1px solid #e6304c;" valign="top"><div style="height:22px;background:#e6304c;">&nbsp;</div></td>
		</tr>
	</table>
		
		                <div style="width:94%;min-width:220px;max-width:650px;margin:0 auto;padding-top:6px;text-align:left;font-family:arial,sans-serif;font-size:13px;line-height:18px;color:#545454;">
			
					<div class="mu-subheader" style="border-bottom:5px solid #fff;">
	<span style="background:#e6304c;color:#fff;border:4px solid #e6304c;text-transform:uppercase;font-size:11px;">New Meetup</span>
	</div>
			<div style="border-top:5px solid #fff;border-bottom:5px solid #fff;text-decoration:none;color:#e6304c;font-size:28px;line-height:30px;font-weight:bold;"><a href="http://www.meetup.com/__ms52304842/The-Edinburgh-Digital-Photography-Meetup-Group/events/128866172/t/ea1_grp/?rv=ea1&_af_eid=128866172&_af=event&expires=1373642893583&sig=5b69c0ee7038f13225950276a14c433a25fe74d1" style="color:#e6304c!important;text-decoration:none;"><font color="#e6304c">National Museum of Scotland, East Kilbride- Heavy Horses Show</font></a></div>
				<div style="border-top:2px solid #fff;border-bottom:6px solid #fff; background:#fff;color:#ccc!important;font-size:18px;">The Edinburgh Digital Photography Meetup Group</div>

										<div style="border-bottom:8px solid #fff; background:#fff;line-height:12px;font-size:12px;">
				Added by Malcolm Park
				</div>
			
			                        <div style="border-top:1px dotted #ccc;overflow:hidden;width:100%;border-bottom:8px solid #fff; background:#fff;">

				<div class="event-meta" style="float:left;width:50%;min-width:220px;border-top:8px solid #fff; background:#fff;">
										<div style="border-bottom:10px solid #fff;border-right:10px solid #fff; background:#fff;">
													<span style="color:#111111;">Sunday, July 14, 2013</span><br>9:45 PM
											</div>
															<div style="border-right:10px solid #fff; background:#fff;">
													<span style="color:#111111;">NMS Museum of rural life</span><br />
							Wester Kittochside, G79 1AA (follow signs)<br/>
																					East Kilbride											</div>
																								</div>
				<div class="event-rsvp-box" style="border-top:8px solid #fff; background:#fff;width:49%; min-width: 200px; float:left;">
																								
							
							
							
																								
							
							
							<table class="event-rsvp-box-status" cellspacing="0" cellpadding="0" style="background-color:#eee;float:right;width:160px;">
        <tr><td style="border-top:8px solid #eee;border-bottom:8px solid #eee;border-left:8px solid #eee;border-right:8px solid #eee; background:#eee;text-align:center;">
                <div style="font-weight:normal;font-size:16px;color:#545454!important;">Will you attend?</div>
		                <div style="font-size:11px;line-height:15px;"></div>
		                <div style="border-top:4px solid #eee; background:#eee;">
                <table class="event-rsvp-box-actions" cellspacing="0" cellpadding="0" style="width:100%;">
									<tr>
										<td style="width:50%;padding-right:4px;">
											<div style="display:block;border:1px solid #9d1328;background-color:#e9003c;-moz-border-radius: 3px 3px 3px 3px;-webkit-border-radius: 3px 3px 3px 3px;border-radius: 3px 3px 3px 3px;text-align:center;"><span class="meetup-button-gradient" style="background-color:#e9003c;display:block;"><a href="http://www.meetup.com/__ms52304842/The-Edinburgh-Digital-Photography-Meetup-Group/events/128866172/t/ea1_lnm/?response=3&fromEmail=128866172&action=rsvp&rv=ea1&_af_eid=128866172&_af=event&refund_policy=true&expires=1373642893583&sig=c90aadcb48cc3d7141974a9adb6e42f05af27379" class="meetup-button-link" style="border-color:#e9003c;border-width:5px 18px;border-style:solid;font-family:arial,sans-serif;font-weight:bold;white-space:nowrap;color:#fff!important;display:block;text-decoration:none;text-align:center;cursor:pointer;"><font color="#fff"><nobr>Yes</nobr></font></a></span></div>
										</td> 
										<td style="width:50%;">
											<div style="display:block;border:1px solid #9d1328;background-color:#e9003c;-moz-border-radius: 3px 3px 3px 3px;-webkit-border-radius: 3px 3px 3px 3px;border-radius: 3px 3px 3px 3px;text-align:center;"><span class="meetup-button-gradient" style="background-color:#e9003c;display:block;"><a href="http://www.meetup.com/__ms52304842/The-Edinburgh-Digital-Photography-Meetup-Group/events/128866172/t/ea1_lnm/?response=2&action=rsvp&rv=ea1&_af_eid=128866172&_af=event&refund_policy=true&expires=1373642893583&sig=0b7163a65ebfb7b210543fb0681472fffdaa20b1" class="meetup-button-link" style="border-color:#e9003c;border-width:5px 18px;border-style:solid;font-family:arial,sans-serif;font-weight:bold;white-space:nowrap;color:#fff!important;display:block;text-decoration:none;text-align:center;cursor:pointer;"><font color="#fff"><nobr>No</nobr></font></a></span></div>
										</td>
									</tr>
                </table>
                </div>
        </td></tr>
</table>
<div style="float:right;width:160px;text-align:center;border-top:10px solid #fff; background:#fff;">
<span style="color:#e6304c;"></span>
</div>

						
									</div>
                        </div>
																					
									
									
										<div style="border-top:1px dotted #ccc;">
					<div style="border-top:8px solid #fff;border-bottom:8px solid #fff; background:#fff;">	
					This is a bit of a last minute idea, NMS are holding a Heavy Horses show near East Kilbride on sunday from 10:00am to 5pm. The horses range from Shetland Ponies up to giant Clydesdales, so this looks like a pretty good day out with some photograp...<br>
					<a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/events/128866172/t/ea1_grp/?rv=ea1" style="color:#06C;text-transform:uppercase;text-decoration:none;font-size:12px;">Learn more</a>
					</div>
				</div>
						
									
			
									
						<div style="background-color:#eee;border-top:10px solid #fff; background:#fff;">
				<div style="background-color:#eee;font-weight:bold;border:8px solid #eee;color:#545454!important;font-size:16px;"><a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/" style="color:#545454!important;text-decoration:none;"><font color="#545454">More Meetups from this group</font></a></div>
				<table cellpadding="0" cellspacing="0" style="width:100%;background-color:#eee;">
									<tr>
	<td class="other-meetups-tearsheet" style="width:32px;background-color:#eee;vertical-align:top;border-top:1px solid #fff;padding:8px 0 8px 8px;">
				<div style="border:1px solid #555;">
			<div style="background-color:#555;text-transform:uppercase;color:#fff!important;font-weight:bold;text-align:center;font-size:9px;line-height:14px;padding:0 4px;"><font color="#fff">Jul</font></div>
			<div style="background-color:#fff;font-size:16px;font-weight:bold;text-align:center;padding:1px 4px 0 4px;">11</div>
		</div>
			</td>
	<td style="vertical-align:top;padding:8px;border-top:1px solid #fff;">
		<table cellpadding="0" cellspacing="0" style="width:100%;">
			<tr>
				<td style="background-color:#eee;vertical-align:top;">
					<a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/events/128061312/t/ea1_evn/?rv=ea1&_af_eid=128061312&_af=event" style="font-size:14px; color: #3987CB; text-decoration: none; ">THEME THURSDAY - Weekly Photography Workshop (Leith Community Education Centre)</a><br/>
					<div style="padding:2px 0 4px 0;font-size:12px;line-height:16px;">
										Thursday, July 11, 2013 1:00 PM	
										&middot;
																				<nobr>3 attending</nobr>
										</div>
				</td>
				<td style="background-color:#eee;width:76px;vertical-align:top;">
					<div style="display:inline-block;border:1px solid #9d1328;background-color:#e9003c;-moz-border-radius: 3px 3px 3px 3px;-webkit-border-radius: 3px 3px 3px 3px;border-radius: 3px 3px 3px 3px;text-align:center;"><span class="meetup-button-gradient" style="background-color:#e9003c;display:inline-block;"><a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/events/128061312/t/ea1_evn/?rv=ea1&_af_eid=128061312&_af=event" class="meetup-button-link" style="border-color:#e9003c;border-width:5px 18px;border-style:solid;font-family:arial,sans-serif;font-weight:bold;white-space:nowrap;color:#fff!important;display:inline-block;text-decoration:none;text-align:center;cursor:pointer;"><font color="#fff"><nobr>RSVP</nobr></font></a></span></div>
				</td>
			</tr>
		</table>
	</td>
</tr>
									<tr>
	<td class="other-meetups-tearsheet" style="width:32px;background-color:#eee;vertical-align:top;border-top:1px solid #fff;padding:8px 0 8px 8px;">
				<div style="border:1px solid #555;">
			<div style="background-color:#555;text-transform:uppercase;color:#fff!important;font-weight:bold;text-align:center;font-size:9px;line-height:14px;padding:0 4px;"><font color="#fff">Jul</font></div>
			<div style="background-color:#fff;font-size:16px;font-weight:bold;text-align:center;padding:1px 4px 0 4px;">14</div>
		</div>
			</td>
	<td style="vertical-align:top;padding:8px;border-top:1px solid #fff;">
		<table cellpadding="0" cellspacing="0" style="width:100%;">
			<tr>
				<td style="background-color:#eee;vertical-align:top;">
					<a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/events/128863862/t/ea1_evn/?rv=ea1&_af_eid=128863862&_af=event" style="font-size:14px; color: #3987CB; text-decoration: none; ">National Museum of Scotland, East Kilbride- Heavy Horses Show</a><br/>
					<div style="padding:2px 0 4px 0;font-size:12px;line-height:16px;">
										Sunday, July 14, 2013 9:30 PM	
										&middot;
																				<nobr>1 attending</nobr>
										</div>
				</td>
				<td style="background-color:#eee;width:76px;vertical-align:top;">
					<div style="display:inline-block;border:1px solid #9d1328;background-color:#e9003c;-moz-border-radius: 3px 3px 3px 3px;-webkit-border-radius: 3px 3px 3px 3px;border-radius: 3px 3px 3px 3px;text-align:center;"><span class="meetup-button-gradient" style="background-color:#e9003c;display:inline-block;"><a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/events/128863862/t/ea1_evn/?rv=ea1&_af_eid=128863862&_af=event" class="meetup-button-link" style="border-color:#e9003c;border-width:5px 18px;border-style:solid;font-family:arial,sans-serif;font-weight:bold;white-space:nowrap;color:#fff!important;display:inline-block;text-decoration:none;text-align:center;cursor:pointer;"><font color="#fff"><nobr>RSVP</nobr></font></a></span></div>
				</td>
			</tr>
		</table>
	</td>
</tr>
									<tr>
	<td class="other-meetups-tearsheet" style="width:32px;background-color:#eee;vertical-align:top;border-top:1px solid #fff;padding:8px 0 8px 8px;">
				<div style="border:1px solid #555;">
			<div style="background-color:#555;text-transform:uppercase;color:#fff!important;font-weight:bold;text-align:center;font-size:9px;line-height:14px;padding:0 4px;"><font color="#fff">Jul</font></div>
			<div style="background-color:#fff;font-size:16px;font-weight:bold;text-align:center;padding:1px 4px 0 4px;">18</div>
		</div>
			</td>
	<td style="vertical-align:top;padding:8px;border-top:1px solid #fff;">
		<table cellpadding="0" cellspacing="0" style="width:100%;">
			<tr>
				<td style="background-color:#eee;vertical-align:top;">
					<a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/events/128064042/t/ea1_evn/?rv=ea1&_af_eid=128064042&_af=event" style="font-size:14px; color: #3987CB; text-decoration: none; ">THEME THURSDAY - Weekly Photography Workshop (Leith Community Education Centre)</a><br/>
					<div style="padding:2px 0 4px 0;font-size:12px;line-height:16px;">
										Thursday, July 18, 2013 1:00 PM	
										&middot;
																				<nobr>2 attending</nobr>
										</div>
				</td>
				<td style="background-color:#eee;width:76px;vertical-align:top;">
					<div style="display:inline-block;border:1px solid #9d1328;background-color:#e9003c;-moz-border-radius: 3px 3px 3px 3px;-webkit-border-radius: 3px 3px 3px 3px;border-radius: 3px 3px 3px 3px;text-align:center;"><span class="meetup-button-gradient" style="background-color:#e9003c;display:inline-block;"><a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/events/128064042/t/ea1_evn/?rv=ea1&_af_eid=128064042&_af=event" class="meetup-button-link" style="border-color:#e9003c;border-width:5px 18px;border-style:solid;font-family:arial,sans-serif;font-weight:bold;white-space:nowrap;color:#fff!important;display:inline-block;text-decoration:none;text-align:center;cursor:pointer;"><font color="#fff"><nobr>RSVP</nobr></font></a></span></div>
				</td>
			</tr>
		</table>
	</td>
</tr>
								</table>
			</div>
						
			
						
<br/>
<div style="background-color:#eee;">
			<div style="border-bottom:1px solid #fff;font-size:13px;">
			<div style="border:8px solid #eee;">
				Sponsored by
																										<span style="white-space:nowrap;line-height:22px;font-size:13px;"><a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/sponsors/" style="color:#0066CC;text-decoration:none;">Calumet Photographic</a>,</span>
																										<span style="white-space:nowrap;line-height:22px;font-size:13px;"><a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/sponsors/" style="color:#0066CC;text-decoration:none;">Ian Millar Photography | Studio Hire</a> and</span>
																										<span style="white-space:nowrap;line-height:22px;font-size:13px;"><a href="http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/sponsors/" style="color:#0066CC;text-decoration:none;">Clear Courses, Edinburgh</a></span>
							</div>
		</div>
				<div style="border:8px solid #eee;">
			<span style="font-size:13px;">Follow us!</span>
							<span style="white-space:nowrap;padding-right:2px;vertical-align:top;"><a href="http://www.facebook.com/home.php?#!/group.php?gid=163198550360757"><img style="vertical-align:middle;" src="http://img1.meetupstatic.com/img/externalservice/socialmediaicons/facebook-16x16.png" width=16 height=16 border=0></a></span>
			
							<span style="white-space:nowrap;padding-right:2px;vertical-align:top;"><a href="http://twitter.com/edpmg/"><img style="vertical-align:middle;" src="http://img1.meetupstatic.com/img/externalservice/socialmediaicons/twitter-16x16.png" width=16 height=16 border=0></a></span>
			
			
			
			
					</div>
	</div>

                </div><br/>
	 	
		                <div style="background:#555;text-align:center;border:5px solid #555">
                        	<div style="clear:both;background:#555;text-align:center;border-top:solid 20px #555;border-bottom:solid 20px #555;">
		<div style="width:94%;margin:0 auto;border-left:solid 10px #555;border-right:solid 10px #555;min-width:220px;max-width:650px;text-align:left;font-family:arial;color:#ccc;font-size:11px;line-height:14px;">
												<p style="margin: 0 0 .25em;color:#ccc;"><a href="http://www.meetup.com/__ms52304842/The-Edinburgh-Digital-Photography-Meetup-Group/optout/?submit=true&email=nuMuMail&expires=1373642893590&sig=ff05c70317f551810ebdedfb7052dea9d39d4073" style="color:#ccc;">Unsubscribe</a> from similar emails from this Meetup Group</p>
										<p style="margin: 0 0 .25em;color:#ccc;">Add <strong><a href="mailto:info@meetup.com" style="color:#ccc;">info@meetup.com</a></strong> to your address book to receive all Meetup emails</p>
			<p style="margin: 0 0 .25em;color:#ccc;"><a href="#" style="color:#ccc;text-decoration:none;cursor:default;">Meetup, POB 4668 #37895 NY NY USA 10163</a></p>
			<p style="margin: 0 0 .25em;color:#ccc;"><strong>Meetup HQ in NYC is hiring!</strong>  <a href="http://www.meetup.com/jobs/" style="color:#ccc;">meetup.com/jobs</a></p>
		</div>
	</div>
                </div>
		
		</div>
        </body>
</html>

------=_Part_10387607_2078989503.1373470093598--

------=_Part_10387606_542281307.1373470093598
Content-Type: text/calendar; name=meetup.ics; method=REQUEST; charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename=meetup.ics

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Meetup//Meetup Events v1.0//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Meetup Events
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:Europe/London
X-LIC-LOCATION:Europe/London
BEGIN:DAYLIGHT
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19700329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19701025T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20130710T152756Z
DTSTART;TZID=Europe/London:20130714T214500
DTEND;TZID=Europe/London:20130715T004500
STATUS:CONFIRMED
SUMMARY:National Museum of Scotland\, East Kilbride- Heavy Horses Show
DESCRIPTION:The Edinburgh Digital Photography Meetup Group\nSunday\, July
  14 at 9:45 PM\n\nThis is a bit of a last minute idea\, NMS are holding 
 a Heavy Horses show near East Kilbride on sunday from 10:00am to 5pm. Th
 e horses range from Shetl...\n\nDetails: http://www.meetup.com/The-Edinb
 urgh-Digital-Photography-Meetup-Group/events/128866172/
ORGANIZER;CN=Meetup Reminder:MAILTO:info@meetup.com
CLASS:PUBLIC
CREATED:20130710T152741Z
GEO:55.97;-3.16
LOCATION:NMS Museum of rural life (Wester Kittochside\, G79 1AA (follow s
 igns)\, East Kilbride\, United Kingdom)
URL:http://www.meetup.com/The-Edinburgh-Digital-Photography-Meetup-Group/
 events/128866172/
LAST-MODIFIED:20130710T152741Z
UID:event_128866172@meetup.com
END:VEVENT
END:VCALENDAR

------=_Part_10387606_542281307.1373470093598--


